config/routes.rb
require 'resque/server'
require 'resque/scheduler'
require 'resque/scheduler/server'

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  mount Resque::Server.new, :at => "/resque"

  resources :comments
  resources :search
  resources :posts do
    resources :comments
  end

  resources :subscriptions
  

  get 'welcome/index'
  get 'welcome/about'
  
  post 'contacts', controller: "welcome", action: :contacts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
  scope "api" do 
    scope "v1" do
      resources :posts, controller: "api/v1/posts" do
        resources :comments, controller: 'api/v1/posts/comments' do
          post 'append-child', action: :append_child
        end
        resources :likes, controller: "api/v1/posts/likes", only: [:create, :destroy]
      end

      resources :users, controller: "api/v1/users" do
        post 'follow', action: :follow
        delete 'unfollow', action: :unfollow
      end

      resources :feed, controller: "api/v1/feed", only: [:index]
    

    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  belongs_to :parent, class_name: 'Comment', foreign_key: 'parent_id', optional: true
  has_many :children, class_name: "Comment", foreign_key: 'parent_id'
end

app/controllers/api/v1/posts/comments_controller.rb
class Api::V1::Posts::CommentsController < Api::V1::ApplicationController
    before_action :set_post


    def index
        @comments = @post.comments
    end

    def create
        @comment = Comment.new(comment_params)
        @comment.post = @post
        @comment.save
    end

    def append_child
        @parent = Comment.find(params[:comment_id])
        @comment_new = Comment.new(comment_params)
        @comment_new.parent = @parent
        @comment_new.post = @post
        @comment_new.save
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:post_id])
    end

    def comment_params
        params.require(:comment).permit(:body, :user_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: %i[ show edit update destroy ]
  load_and_authorize_resource

  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @comment = Comment.new(post_id: params[:post_id])
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_url(@comment.post), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy 
    @comment.destroy 
 
    respond_to do |format| 
      format.html { redirect_to post_path(@comment.post_id) } 
      format.json { head :no_content } 
    end 
  end


  private

    def comment_params
      params.require(:comment).permit(:commenter, :body, :post_id)
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>" class="comments_item_container">
  
<div class="comments_right_part">
  <div class ="commentor-picture">
    <% if comment.user.logo.present? %> 
        <%= image_tag comment.user.logo.url %>
         <% else %>
         <%= image_tag "Commentor.png" %>
      <% end %>
  </div>
  
  <div class="comment_body_cont">

  <div class ="comment_top">
    <p class="commentor-email">
    <%= comment.user.email %>
  </p>
  <p class="comments_text_date">
    <%= comment.created_at %>
  </p>
  </div>

  <p class="comments_text">
    <%= comment.body %>
  </p>
  </div>
  </div>

  <% if can? :manage, comment %> 
  <div class="comment_buttons"> 
  <%= link_to "Редактировать", edit_comment_path(comment), class: "manage_button_comment" %>
  <%= link_to "Удалить", comment, data: {turbo_method: :delete}, class: "manage_button_comment"%>
</div>
<% end %>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: @comment) do |form| %>
  <div class="input-button-container">
  <%= form.text_area :body, placeholder: "Добавить комментарий" %>
  <%= form.submit 'Отправить' %>
  </div>

  <div>
    <%= form.hidden_field :post_id, value: @comment.post_id || post_id %>
  </div>

<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment, class: "manage_button" %> 
  <%= link_to "Back to comments", comments_path, class: "manage_button" %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
  <% end %>
</div>


app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path, class: "manage_button" %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment), class: "manage_button"%> |
  <%= link_to "Back to comments", comments_path, class: "manage_button" %>

  <%= link_to "Destroy this comment", @comment, class: "manage_button", data: {turbo_method: :delete} %>
</div>