config/routes.rb
require 'resque/server'
require 'resque/scheduler'
require 'resque/scheduler/server'

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  mount Resque::Server.new, :at => "/resque"

  resources :comments
  resources :search
  resources :posts do
    resources :comments
  end

  resources :subscriptions
  

  get 'welcome/index'
  get 'welcome/about'
  
  post 'contacts', controller: "welcome", action: :contacts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
  scope "api" do 
    scope "v1" do
      resources :posts, controller: "api/v1/posts" do
        resources :comments, controller: 'api/v1/posts/comments' do
          post 'append-child', action: :append_child
        end
        resources :likes, controller: "api/v1/posts/likes", only: [:create, :destroy]
      end

      resources :users, controller: "api/v1/users" do
        post 'follow', action: :follow
        delete 'unfollow', action: :unfollow
      end

      resources :feed, controller: "api/v1/feed", only: [:index]
    

    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
	acts_as_taggable_on :tags
	validates :name, :presence => true
	validates :title, :presence => true, :length => { :minimum => 5, :maximum => 63}

	has_many :comments, :dependent => :destroy
	mount_uploader :post_image, PostImageUploader
	belongs_to :user
	has_many :post_likes
	def likes_count 
		post_likes.size
	end
end

app/controllers/api/v1/posts/comments_controller.rb
class Api::V1::Posts::CommentsController < Api::V1::ApplicationController
    before_action :set_post


    def index
        @comments = @post.comments
    end

    def create
        @comment = Comment.new(comment_params)
        @comment.post = @post
        @comment.save
    end

    def append_child
        @parent = Comment.find(params[:comment_id])
        @comment_new = Comment.new(comment_params)
        @comment_new.parent = @parent
        @comment_new.post = @post
        @comment_new.save
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:post_id])
    end

    def comment_params
        params.require(:comment).permit(:body, :user_id)
    end
end

app/controllers/api/v1/posts/likes_controller.rb
class Api::V1::Posts::LikesController < Api::V1::ApplicationController  
  before_action :set_post
    def create
      @like = PostLike.find_or_create_by(post_id: @post.id, user_id: params[:user_id])
    end
    def destroy    
        @like = PostLike.find_by(id: params[:id])
        @like.destroy! if @like.present?  
    end
    private

    # Use callbacks to share common setup or constraints between actions.  
    def set_post
      @post = Post.find(params[:post_id]) 
    end
  end
  

app/controllers/api/v1/posts/search_controller.rb
class Api::V1::Posts::SearchController < Api::V1::ApplicationController
    before_action :permitted_params
  
    def search
      @posts = Post.where("name LIKE :query", query: "%#{params[:q]}%")
  
      respond_to do |format|
        format.turbo_stream
      end
    end
  
    private
  
    def permitted_params
      params.permit(:q)
    end
  end  

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::ApplicationController
    before_action :set_post, only: %i[ show edit update destroy ]


    def index
        @posts = Post.all
        relation = PostLike.where(post_id: @posts.map(&:id))        
        relation = relation.where(user_id: params[:user_id]) if params[:user_id].present?
        @post_likes = {}.tap do |hash|            
            relation.each do |like|
                hash[like.post_id] = {
                    liked: params[:user_id].present? ? like.id : nil, 
                    likes_count: like.post.likes_count
            }
            end
        end
    end
   
    def show
        @comments = @post.comments
        @liked = @post.post_likes.where(user_id: params[:user_id]).present?
    end

    def create
        @post = Post.new(post_params)
        @post.user = User.first
        @post.save
    end


    private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def post_param
        params.require(:post).permit(:name, :title, :content, :post_image)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  #before_action :authenticate_user!
  #load_and_authorize_resource

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment=Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    @post.assign_attributes(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :title, :author, :content, :post_image, :tag_list)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>


  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :post_image, style: "display: block" %>
    <%= form.file_field :post_image %>
  </div>

    <div>
    <%= form.label :tag_list, style: "display: block" %>
    <%= form.text_field :tag_list, value: post.tag_list %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>


app/views/posts/_post.html.erb



<div class="post-page-wrapper">
<div class='posts-item-content'> 
  <% if post.user.logo.present? %> 
    <%= image_tag post.user.logo.url, class: "post-user-logo" %> 
  <% end %> 
  <p class="post-user-text"> 
     <%= post.user.name %> 
  </p> 
</div>

  <div id="<%= dom_id post %>" class="post-item-container">
  <div class="post-item-image">
  <% if post.post_image.present? %>
  <%= image_tag post.post_image.url, width: 100 %>
  <% end %>
  </div>

  <div class="post-item-content">
  
  <div class="top-item-content">
  <p class="post-item-title">
    <%= post.title %>
  </p>

  <div class="tags_container">
  <% post.tag_list.each do |tag| %>
    <p class="post-tag-text">
    <%= tag %>
    </p>
  <% end%>
  </div>

  <p class ="post-item-text">
    <%= post.content %>
  </p>
  </div>

<div class="likes_count_container">
  <div class="likes_number_container">

<a class="navigation-link" onclick="like_post(post_id)" id='liked'>
  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M7.5 4.5C5.27956 4.5 3.5 6.26849 3.5 8.425C3.5 10.2648 4.4339 12.0808 6.10998 14.0356C7.6813 15.8681 9.82573 17.7334 12.25 19.771C14.6743 17.7334 16.8187 15.8681 18.39 14.0356C20.0661 12.0808 21 10.2648 21 8.425C21 6.26849 19.2204 4.5 17 4.5C15.1557 4.5 13.4547 5.70819 12.9659 7.27292C12.8681 7.58607 12.5781 7.79929 12.25 7.79929C11.9219 7.79929 11.6319 7.58607 11.5341 7.27292C11.0453 5.70819 9.34435 4.5 7.5 4.5ZM2 8.425C2 5.41765 4.47373 3 7.5 3C9.37658 3 11.1948 3.93637 12.25 5.40244C13.3052 3.93637 15.1234 3 17 3C20.0263 3 22.5 5.41765 22.5 8.425C22.5 10.7927 21.2964 12.9504 19.5287 15.0119C17.7596 17.0752 15.3352 19.1437 12.7317 21.3249C12.453 21.5584 12.047 21.5584 11.7683 21.3249C9.16484 19.1437 6.7404 17.0752 4.97127 15.0119C3.2036 12.9504 2 10.7927 2 8.425Z" fill="#F7F7F7"/>
</svg>
</a>

<a class="navigation-link" onclick="delete_post(post_id)" id='disliked'>
  <svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M11.5 8.5C9.27956 8.5 7.5 10.2685 7.5 12.425C7.5 14.2648 8.4339 16.0808 10.11 18.0356C11.6813 19.8681 13.8257 21.7334 16.25 23.771C18.6743 21.7334 20.8187 19.8681 22.39 18.0356C24.0661 16.0808 25 14.2648 25 12.425C25 10.2685 23.2204 8.5 21 8.5C19.1557 8.5 17.4547 9.70819 16.9659 11.2729C16.8681 11.5861 16.5781 11.7993 16.25 11.7993C15.9219 11.7993 15.6319 11.5861 15.5341 11.2729C15.0453 9.70819 13.3443 8.5 11.5 8.5ZM6 12.425C6 9.41765 8.47373 7 11.5 7C13.3766 7 15.1948 7.93637 16.25 9.40244C17.3052 7.93637 19.1234 7 21 7C24.0263 7 26.5 9.41765 26.5 12.425C26.5 14.7927 25.2964 16.9504 23.5287 19.0119C21.7596 21.0752 19.3352 23.1437 16.7317 25.3249C16.453 25.5584 16.047 25.5584 15.7683 25.3249C13.1648 23.1437 10.7404 21.0752 8.97127 19.0119C7.2036 16.9504 6 14.7927 6 12.425Z" fill="#EF2743"/>
<path d="M8.5 16.5L16.5 24.5L19 23L24 18.5L26 14.5V11.5L25 9L22.5 8H20.5L19 8.5L16.5 10.5L15.5 9L13.5 8H10L7.5 10L7 13L8.5 16.5Z" fill="#EF2743"/>
</svg>

</a>

<p class="likes_count">
  <%= post.likes_count %>
</p>

</div>

<div id='link_copied' class='post-item-text'>
  <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M18 10C18 14.4183 14.4183 18 10 18C5.58172 18 2 14.4183 2 10C2 5.58172 5.58172 2 10 2C14.4183 2 18 5.58172 18 10ZM13.6206 6.62347C13.9667 6.85109 14.0627 7.31615 13.8351 7.66222L10.4278 12.9698C9.95945 13.6993 9.72529 14.0641 9.38051 14.1097C9.34307 14.1147 9.3053 14.1168 9.26753 14.1161C8.91981 14.1093 8.64623 13.7731 8.09907 13.1007L6.51804 11.1578C6.25684 10.8363 6.3057 10.3639 6.62718 10.1027C6.94865 9.84153 7.42101 9.8904 7.68221 10.2119L9.29118 12.1907C9.29118 12.1907 11.6324 8.28159 12.5819 6.83795C12.8095 6.49188 13.2746 6.39585 13.6206 6.62347Z" fill="#F7F7F7"/>
</svg>
  <p class="tooltip_text" >Ссылка скопирована</p>
</div>

<a class='navigation-link' onclick="myCopyContent()">
<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M18.4782 13.0247L17.0974 13.1347C12.521 13.4995 9.01282 16.7674 7.87205 21.4487C11.2081 18.4956 14.6963 18.1 16.9782 18.1H18.4782L18.4782 22.5L24.9068 15.75L18.4782 9V13.0247ZM26.19 14.9224C26.4672 15.2134 26.6058 15.359 26.658 15.5252C26.704 15.6715 26.704 15.8285 26.658 15.9748C26.6058 16.1411 26.4672 16.2866 26.19 16.5776L18.3575 24.8017C17.9269 25.2539 17.7116 25.4799 17.5259 25.4977C17.3649 25.5132 17.2063 25.4497 17.1004 25.3275C16.9782 25.1865 16.9782 24.8744 16.9782 24.25L16.9782 19.6C16.5238 19.6 16.0197 19.6165 15.4782 19.6706C13.188 19.8992 10.1877 20.8441 7.46288 24.0055C7.36886 24.1155 7.27512 24.2281 7.18171 24.3435C7.05248 24.5031 6.85804 24.6 6.65265 24.6C6.28161 24.6 5.98077 24.2964 6.00096 23.9259C6.01026 23.7552 6.02222 23.5854 6.0368 23.4167C6.60557 17.0597 10.9023 12.1238 16.9782 11.6395V7.25C16.9782 6.62564 16.9782 6.31346 17.1004 6.17251C17.2063 6.05027 17.3649 5.98684 17.5259 6.00229C17.7116 6.0201 17.9269 6.24616 18.3575 6.69828L26.19 14.9224Z" fill="#F7F7F7"/>
</svg>

</a>

<script> 
 var post_liked = !!'<%= current_user ? current_user.post_liked?(post) : false %>' 
 var user_id = <%= current_user&.id || 0 %> 
 var post_id = <%= post.id %> 
 
taggle_like() 
 
function taggle_like() { 
  var liked_tag = document.getElementById("liked"); 
  var disliked_tag = document.getElementById("disliked"); 
 
  if (post_liked) { 
    liked_tag.hidden = true 
    disliked_tag.hidden = false 
  } else { 
    liked_tag.hidden = false 
    disliked_tag.hidden = true 
  } 
} 
</script>


</div>


</div>
</div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post, class: "manage_button" %> |
  <%= link_to "Back to posts", posts_path, class: "manage_button" %>
</div>

app/views/posts/index.html.erb
<main> 
  <div class="posts-wrapper">
  <div id="posts"> 
  <% @posts.each_with_index do |post, i| %> 
   <% if i % 9 == 0 %> 
   <div class="posts-container"> 
    <% end %> 
    <%= link_to post, class: "post-#{i % 9}" do %>
    <div class="post-container-"> 
      <% if post.post_image.present? %> 
        <%= image_tag post.post_image.url %> 
      <% end %> 
      <div class='posts-item-content'> 
          <%= image_tag post.user.logo.url, class: "post-user-logo" %> 
        <p class="post-user-text"> 
          <%= post.user.name %> 
        </p> 

      </div> 
      </div>

    <% end %> 
    <% if i % 9 == 8 %> 
      </div> 
    <% end %> 
  <% end %> 
  </div>
</main>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path, class: "manage_button" %>
</div>

app/views/posts/show.html.erb



<div class="post_row_container">

<div class="back_to_posts_arrow">
<%= link_to posts_url do %>
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M11.1855 4.24063C11.4852 3.91979 11.984 3.91979 12.2942 4.24063C12.5939 4.55063 12.5939 5.06657 12.2942 5.37585L6.67228 11.1907H19.2238C19.6563 11.1914 20 11.5469 20 11.9942C20 12.4415 19.6563 12.8086 19.2238 12.8086H6.67228L12.2942 18.6126C12.5939 18.9334 12.5939 19.4501 12.2942 19.7594C11.984 20.0802 11.4845 20.0802 11.1855 19.7594L4.23265 12.568C3.92245 12.258 3.92245 11.742 4.23265 11.4328L11.1855 4.24063Z" fill="#F7F7F7"/>
</svg>
<% end %>
</div>


  <div class="post_column_container">
    <%= render @post %>



    <div class ="comments_form_container">
      <%= render "comments/form", post_id: @post.id %>
    </div>


    <%= render @post.comments.order(created_at: :desc) %>

    <div>
      <%= link_to "Back to posts", posts_path, class: "manage_button" %>

      <% if can? :manage, @post %> 
        <%= link_to "Delete this post", @post, data: {turbo_method: :delete}, class: "manage_button"%>
        <%= link_to "Edit this post", edit_post_path(@post), class: "manage_button" %>
      <% end %>
    </div>


  </div>
</div>