config/routes.rb
require 'resque/server'
require 'resque/scheduler'
require 'resque/scheduler/server'

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  mount Resque::Server.new, :at => "/resque"

  resources :comments
  resources :search
  resources :posts do
    resources :comments
  end

  resources :subscriptions
  

  get 'welcome/index'
  get 'welcome/about'
  
  post 'contacts', controller: "welcome", action: :contacts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
  scope "api" do 
    scope "v1" do
      resources :posts, controller: "api/v1/posts" do
        resources :comments, controller: 'api/v1/posts/comments' do
          post 'append-child', action: :append_child
        end
        resources :likes, controller: "api/v1/posts/likes", only: [:create, :destroy]
      end

      resources :users, controller: "api/v1/users" do
        post 'follow', action: :follow
        delete 'unfollow', action: :unfollow
      end

      resources :feed, controller: "api/v1/feed", only: [:index]
    

    end
  end
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<footer>
        <div class="footer_content">
        <div class="footer_left_part">
        <svg width="82" height="20" viewBox="0 0 82 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M0 0.268519H9.75178V2.55093H2.53223V8.51204H9.213V10.8213H2.53223V19.0648H0V0.268519Z" fill="#F7F7F7"/>
<path d="M18.3597 0.0537047H19.7875L27.5997 19.0648H24.825L22.9123 14.2315H15.154L13.2683 19.0648H10.6283L18.3597 0.0537047ZM16.0161 12.0296H22.0234L19.0062 4.43056L16.0161 12.0296Z" fill="#F7F7F7"/>
<path d="M26.2016 0.805556V0.268519H28.7338L34.4179 14.2852L40.048 0.268519H42.4456V0.805556L34.8219 19.3065H33.8252L26.2016 0.805556Z" fill="#F7F7F7"/>
<path d="M47.8333 19.0648H45.3011V0.268519H47.8333V19.0648Z" fill="#F7F7F7"/>
<path d="M58.4782 0.0537047H59.906L67.7182 19.0648H64.9435L63.0309 14.2315H55.2725L53.3868 19.0648H50.7469L58.4782 0.0537047ZM56.1346 12.0296H62.1419L59.1248 4.43056L56.1346 12.0296Z" fill="#F7F7F7"/>
<path d="M75.0836 19.3333C73.5391 19.3333 72.255 19.0559 71.2314 18.5009C70.2077 17.9281 69.3906 17.2568 68.7799 16.487L70.5579 14.6074C71.0967 15.2877 71.7342 15.8515 72.4705 16.2991C73.2069 16.7466 74.0958 16.9704 75.1375 16.9704C76.3228 16.9704 77.2117 16.6929 77.8044 16.138C78.397 15.5651 78.6934 14.8222 78.6934 13.9093C78.6934 13.1037 78.4689 12.4682 78.0199 12.0028C77.5889 11.5194 77.0321 11.1167 76.3497 10.7944C75.6852 10.4543 74.9668 10.15 74.1946 9.88148C73.4224 9.59506 72.695 9.25494 72.0126 8.86111C71.3481 8.44938 70.7914 7.9392 70.3424 7.33056C69.9114 6.72191 69.6959 5.90741 69.6959 4.88704C69.6959 4.13519 69.8306 3.45494 70.0999 2.8463C70.3873 2.23766 70.7734 1.72747 71.2583 1.31574C71.7612 0.886111 72.3628 0.563889 73.0632 0.349074C73.7815 0.116358 74.5717 0 75.4338 0C76.7448 0 77.8313 0.241667 78.6934 0.725001C79.5554 1.19043 80.2468 1.71852 80.7676 2.30926L79.1782 4.00093C78.7113 3.51759 78.1725 3.12377 77.5619 2.81945C76.9693 2.49722 76.2509 2.33611 75.4068 2.33611C74.4191 2.33611 73.6469 2.55093 73.0901 2.98056C72.5514 3.41019 72.282 4.00093 72.282 4.75278C72.282 5.43303 72.5065 5.97901 72.9554 6.39074C73.4044 6.80247 73.9611 7.16049 74.6256 7.46482C75.2901 7.76914 76.0175 8.06451 76.8077 8.35093C77.5979 8.63735 78.3252 9.00432 78.9897 9.45185C79.6542 9.88148 80.2109 10.4275 80.6599 11.0898C81.1088 11.7522 81.3333 12.6114 81.3333 13.6676C81.3333 14.5985 81.1717 15.4219 80.8484 16.138C80.5252 16.8361 80.0852 17.4269 79.5284 17.9102C78.9717 18.3756 78.3072 18.7336 77.535 18.9843C76.7807 19.217 75.9636 19.3333 75.0836 19.3333Z" fill="#F7F7F7"/>
        </svg>
        <p class="left_part_text">Since 2023</p>
        </div>
        <div class="footer_right_part">
        <div class="first_point">
            <p class="footer_title">Маркетплейс</p>
            <ul class="first_point_list">
                <li class="first_point_item">Каталог товаров</li>
                <li class="first_point_item">Бренды</li>
            </ul>
        </div>
         <div class="second_point">
            <p class="footer_title">Keep in touch!</p>
            <ul class="first_point_list">
                <li class="first_point_item">Группа VK</li>
                <li class="first_point_item">YouTube канал</li>
                <li class="first_point_item">favias.market@yandex.ru</li>
            </ul>
         </div>
        </div>

        </div>
    </footer>

app/views/application/_menubar.html.erb
<header class="header">
  <div class="header__container">
    <div class="header__logo">
    <%= link_to welcome_index_url, class: "logo__image" do %>
    <%= image_tag "S_Logo.svg" %>
    <% end %>
    </div>

    <nav class="menu header__menu">
      <ul class="menu__list">
        <li class="menu__item"><%= link_to "Рекомендации", posts_url, class: "menu__link" %></li>
        <% if current_user %>
        <li class="menu__item"><%= link_to "Твои подписки", posts_url, class: "menu__link" %></li>
        <% end %>
        <li class="menu__item"><a class="menu__link" href="studios.html">Маркетплейс favias</a>
          <svg width="21" height="20" viewBox="0 0 21 20" fill="none" xmlns="http://www.w3.org/2000/svg">
						<path fill-rule="evenodd" clip-rule="evenodd"
						d="M4.63965 15.8603C4.93255 16.1532 5.40742 16.1532 5.70031 15.8603L14.0033 7.55735V13.6634C14.0033 14.0776 14.3391 14.4134 14.7533 14.4134C15.1675 14.4134 15.5033 14.0776 15.5033 13.6634V5.74669C15.5033 5.33247 15.1675 4.99669 14.7533 4.99669H6.83665C6.42244 4.99669 6.08665 5.33247 6.08665 5.74669C6.08665 6.1609 6.42244 6.49669 6.83665 6.49669H12.9427L4.63965 14.7997C4.34676 15.0926 4.34676 15.5675 4.63965 15.8603Z"
						fill="#F7F7F7" />
					</svg>
        </li>
      </ul>
  </nav>

  <div class="search-box header__search-box">
				<form action="/search" method="GET" class="search-box__form">
					<input type="text" name="query" placeholder="Поиск" class="search-box__input">
				</form>
			</div>


<% if current_user %>
			<div class="header__actions">
				<button class="notifications__button">
          <svg width="41" height="40" viewBox="0 0 41 40" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M13.1429 21.144C12.8354 22.0512 12.2215 22.6837 11.6739 23.2479C11.033 23.9083 10.4829 24.4751 10.6216 25.2792C10.8245 26.4555 12.3679 26.4416 13.2371 26.4337L16.7954 26.4325C16.9215 28.3687 18.5319 29.9001 20.5 29.9001C22.468 29.9001 24.0784 28.3687 24.2045 26.4325L27.7628 26.4337C28.6321 26.4416 30.1755 26.4555 30.3784 25.2792C30.5171 24.4751 29.967 23.9083 29.326 23.2479C28.7785 22.6837 28.1646 22.0512 27.857 21.144C27.4676 19.9952 27.2756 18.0201 26.935 16.0025C26.44 13.0701 24.46 10.1001 20.5 10.1001C16.54 10.1001 14.56 13.0701 14.065 16.0025C13.7366 17.9476 13.5324 19.9952 13.1429 21.144ZM12.1843 24.8942C12.2835 24.7614 12.4582 24.5705 12.7496 24.2726C13.2823 23.728 14.128 22.8635 14.5493 21.6208C15.1308 19.9054 15.2293 18.0266 15.5293 16.2497C15.7395 15.004 16.2559 13.822 17.0606 12.9736C17.835 12.157 18.9318 11.5851 20.5 11.5851C22.0681 11.5851 23.1649 12.157 23.9394 12.9736C24.7441 13.822 25.2604 15.004 25.4707 16.2497C25.772 18.0348 25.8672 19.8996 26.4507 21.6208C26.872 22.8635 27.7176 23.728 28.2504 24.2726C28.5417 24.5705 28.7164 24.7614 28.8156 24.8942C28.4092 24.9728 27.9883 24.9475 27.5769 24.9475H13.423C13.0116 24.9475 12.5908 24.9728 12.1843 24.8942ZM22.7142 26.4325H18.2858C18.4077 27.5475 19.3525 28.4151 20.5 28.4151C21.6474 28.4151 22.5922 27.5475 22.7142 26.4325Z" fill="#F7F7F7"/>
</svg>
			
        </button>

				<button class="create__button">Создать Айтем</button>
				
        
          <%= link_to edit_user_registration_path, class: "round__button" do %> 
            <%= image_tag current_user.logo.url, class: "round__button-icon", alt: "Лого пользователя"%>  
          <% end %> 
        <% else %> 
          <%= link_to "Войти", new_user_session_path, class: "menu__link" %> 
        <% end %>



			</div>

      </div>

</header>